/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_hylanda_lightgrep_NativeLibrary */

#ifndef _Included_com_hylanda_lightgrep_NativeLibrary
#define _Included_com_hylanda_lightgrep_NativeLibrary
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_hylanda_lightgrep_NativeLibrary
 * Method:    parsePattern
 * Signature: (Ljava/lang/String;I)J
 */
JNIEXPORT jlong JNICALL Java_com_hylanda_lightgrep_NativeLibrary_parsePattern
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     com_hylanda_lightgrep_NativeLibrary
 * Method:    releasePattern
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_hylanda_lightgrep_NativeLibrary_releasePattern
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_hylanda_lightgrep_NativeLibrary
 * Method:    createVsmStates
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_com_hylanda_lightgrep_NativeLibrary_createVsmStates
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_hylanda_lightgrep_NativeLibrary
 * Method:    addPattern
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_com_hylanda_lightgrep_NativeLibrary_addPattern
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_hylanda_lightgrep_NativeLibrary
 * Method:    releaseVsmStates
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_hylanda_lightgrep_NativeLibrary_releaseVsmStates
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_hylanda_lightgrep_NativeLibrary
 * Method:    createAutomation
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_hylanda_lightgrep_NativeLibrary_createAutomation
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_hylanda_lightgrep_NativeLibrary
 * Method:    getAutomationSize
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_hylanda_lightgrep_NativeLibrary_getAutomationSize
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_hylanda_lightgrep_NativeLibrary
 * Method:    getAutomationBuffer
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_hylanda_lightgrep_NativeLibrary_getAutomationBuffer
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_hylanda_lightgrep_NativeLibrary
 * Method:    applyAutomationBuffer
 * Signature: (J[BII)Z
 */
JNIEXPORT jboolean JNICALL Java_com_hylanda_lightgrep_NativeLibrary_applyAutomationBuffer
  (JNIEnv *, jclass, jlong, jbyteArray, jint, jint);

/*
 * Class:     com_hylanda_lightgrep_NativeLibrary
 * Method:    releaseAutomation
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_hylanda_lightgrep_NativeLibrary_releaseAutomation
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_hylanda_lightgrep_NativeLibrary
 * Method:    createMatcher
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_hylanda_lightgrep_NativeLibrary_createMatcher
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_hylanda_lightgrep_NativeLibrary
 * Method:    releaseMatcher
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_hylanda_lightgrep_NativeLibrary_releaseMatcher
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_hylanda_lightgrep_NativeLibrary
 * Method:    matchText
 * Signature: (JJLcom/hylanda/lightgrep/HitsCallback;)V
 */
JNIEXPORT void JNICALL Java_com_hylanda_lightgrep_NativeLibrary_matchText
  (JNIEnv *, jclass, jlong, jlong, jobject);

/*
 * Class:     com_hylanda_lightgrep_NativeLibrary
 * Method:    startWithText
 * Signature: (JJIILcom/hylanda/lightgrep/HitsCallback;)V
 */
JNIEXPORT void JNICALL Java_com_hylanda_lightgrep_NativeLibrary_startWithText
  (JNIEnv *, jclass, jlong, jlong, jint, jint, jobject);

/*
 * Class:     com_hylanda_lightgrep_NativeLibrary
 * Method:    matchBuffer
 * Signature: (J[BIILcom/hylanda/lightgrep/HitsCallback;)V
 */
JNIEXPORT void JNICALL Java_com_hylanda_lightgrep_NativeLibrary_matchBuffer
  (JNIEnv *, jclass, jlong, jbyteArray, jint, jint, jobject);

/*
 * Class:     com_hylanda_lightgrep_NativeLibrary
 * Method:    createStringBuffer
 * Signature: ([B)J
 */
JNIEXPORT jlong JNICALL Java_com_hylanda_lightgrep_NativeLibrary_createStringBuffer
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     com_hylanda_lightgrep_NativeLibrary
 * Method:    releaseStringBuffer
 * Signature: ([BJ)V
 */
JNIEXPORT void JNICALL Java_com_hylanda_lightgrep_NativeLibrary_releaseStringBuffer
  (JNIEnv *, jclass, jbyteArray, jlong);

#ifdef __cplusplus
}
#endif
#endif
